<?php
require_once __DIR__.'/_common.php'; $adminTitle='Emergency Management'; checkPostCsrf();
if($_SERVER['REQUEST_METHOD']==='POST'){ $id=postInt('id');$status=postString('status'); if(in_array($status,['New','Investigating','Resolved'],true)){ $pdo->prepare("UPDATE emergency_reports SET status=?,resolved_at=? WHERE id=?")->execute([$status,$status==='Resolved'?date('Y-m-d H:i:s'):null,$id]);adminLog($status==='Resolved'?'Emergency resolved':'Emergency status changed','emergency',$id,$status);flash('success','Emergency status updated.');} adminRedirect('emergencies.php');}
$q=trim($_GET['q']??'');$severity=$_GET['severity']??'';$status=$_GET['status']??'';$sql="SELECT e.*,u.name driver,b.bus_number,r.route_code FROM emergency_reports e JOIN users u ON u.id=e.driver_id JOIN buses b ON b.id=e.bus_id JOIN routes r ON r.id=e.route_id WHERE 1";$p=[];if($q!==''){$sql.=" AND (e.title LIKE ? OR e.description LIKE ? OR b.bus_number LIKE ? OR u.name LIKE ?)";$p=["%$q%","%$q%","%$q%","%$q%"];}if(in_array($severity,['Low','Medium','High','Critical'],true)){$sql.=" AND e.severity=?";$p[]=$severity;}if(in_array($status,['New','Investigating','Resolved'],true)){$sql.=" AND e.status=?";$p[]=$status;}$sql.=" ORDER BY FIELD(e.severity,'Critical','High','Medium','Low'),e.created_at DESC";$st=$pdo->prepare($sql);$st->execute($p);$rows=$st->fetchAll();require __DIR__.'/_layout.php';
?>
<div class="admin-page-head"><div><span class="admin-kicker">INCIDENT CONTROL</span><h2>Emergency Management</h2><p>Review and resolve driver-submitted emergency reports.</p></div></div>
<form class="admin-filters" method="get"><input name="q" value="<?= e($q) ?>" placeholder="Search title, driver or bus"><select name="severity"><option value="">All severity</option><?php foreach(['Critical','High','Medium','Low'] as $v): ?><option <?= $severity===$v?'selected':'' ?>><?= $v ?></option><?php endforeach; ?></select><select name="status"><option value="">All status</option><?php foreach(['New','Investigating','Resolved'] as $v): ?><option <?= $status===$v?'selected':'' ?>><?= $v ?></option><?php endforeach; ?></select><button class="admin-btn">Filter</button></form>
<section class="admin-panel"><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Incident</th><th>Severity</th><th>Bus / Route</th><th>Driver</th><th>Description</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr class="<?= strtolower($r['severity'])==='critical'?'critical-row':'' ?>"><td><strong><?= e($r['title']) ?></strong><small><?= e($r['created_at']) ?></small></td><td><?= statusBadge($r['severity']) ?></td><td><?= e($r['bus_number']) ?><small><?= e($r['route_code']) ?></small></td><td><?= e($r['driver']) ?></td><td class="desc-cell"><?= e($r['description']) ?></td><td><form method="post" class="inline-form"><input type="hidden" name="csrf_token" value="<?= e(csrfToken()) ?>"><input type="hidden" name="id" value="<?= $r['id'] ?>"><select name="status" onchange="this.form.submit()"><?php foreach(['New','Investigating','Resolved'] as $v): ?><option <?= $r['status']===$v?'selected':'' ?>><?= $v ?></option><?php endforeach; ?></select></form></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php require __DIR__.'/_layout_end.php'; ?>
