<?php
require_once __DIR__.'/_common.php'; $adminTitle='Notice Management'; checkPostCsrf();
if($_SERVER['REQUEST_METHOD']==='POST'){
 $a=postString('action');$id=postInt('id');
 try{
  if($a==='save'){ $title=postString('title');$message=postString('message');$type=postString('notice_type');$priority=postString('priority');$status=postString('status','active');if($title===''||$message==='')throw new Exception('Title and message are required.');if(!in_array($type,['information','warning','emergency'],true)||!in_array($priority,['low','medium','high'],true))throw new Exception('Invalid notice options.');
   if($id)$pdo->prepare("UPDATE notices SET title=?,message=?,notice_type=?,priority=?,status=? WHERE id=?")->execute([$title,$message,$type,$priority,$status,$id]);else{$pdo->prepare("INSERT INTO notices(title,message,notice_type,priority,status) VALUES(?,?,?,?,?)")->execute([$title,$message,$type,$priority,$status]);$id=(int)$pdo->lastInsertId();}adminLog('Notice saved','notice',$id,$title);flash('success','Notice saved.');
  }elseif($a==='toggle'){$pdo->prepare("UPDATE notices SET status=IF(status='active','inactive','active') WHERE id=?")->execute([$id]);adminLog('Notice status changed','notice',$id);flash('success','Notice status updated.');}
 }catch(Throwable $e){flash('error',$e->getMessage());}adminRedirect('notices.php');
}
$edit=null;if(isset($_GET['edit'])){$st=$pdo->prepare("SELECT * FROM notices WHERE id=?");$st->execute([(int)$_GET['edit']]);$edit=$st->fetch();}
$rows=$pdo->query("SELECT * FROM notices ORDER BY created_at DESC")->fetchAll();require __DIR__.'/_layout.php';
?>
<div class="admin-page-head"><div><span class="admin-kicker">COMMUNICATION</span><h2>Service Notices</h2><p>Publish passenger-facing information, warnings and emergency notices.</p></div></div>
<div class="admin-grid-2"><section class="admin-panel"><div class="admin-panel-head"><h3><?= $edit?'Edit Notice':'Create Notice' ?></h3></div><form method="post" class="admin-form"><input type="hidden" name="csrf_token" value="<?= e(csrfToken()) ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><label>Title<input required name="title" value="<?= e($edit['title']??'') ?>"></label><label>Message<textarea required name="message"><?= e($edit['message']??'') ?></textarea></label><label>Type<select name="notice_type"><?php foreach(['information','warning','emergency'] as $v): ?><option <?= ($edit['notice_type']??'information')===$v?'selected':'' ?>><?= $v ?></option><?php endforeach; ?></select></label><label>Priority<select name="priority"><?php foreach(['low','medium','high'] as $v): ?><option <?= ($edit['priority']??'low')===$v?'selected':'' ?>><?= $v ?></option><?php endforeach; ?></select></label><label>Status<select name="status"><option value="active" <?= ($edit['status']??'active')==='active'?'selected':'' ?>>Published</option><option value="inactive" <?= ($edit['status']??'')==='inactive'?'selected':'' ?>>Unpublished</option></select></label><button class="admin-btn">Save Notice</button></form></section>
<section class="admin-panel"><div class="admin-panel-head"><h3>Published & draft notices</h3></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Notice</th><th>Type</th><th>Priority</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><strong><?= e($r['title']) ?></strong><small><?= e($r['message']) ?></small></td><td><?= statusBadge($r['notice_type']) ?></td><td><?= statusBadge($r['priority']) ?></td><td><?= statusBadge($r['status']) ?></td><td><?= e($r['created_at']) ?></td><td class="action-links"><a href="?edit=<?= $r['id'] ?>">Edit</a><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrfToken()) ?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?= $r['id'] ?>"><button>Publish/Hide</button></form></td></tr><?php endforeach; ?></tbody></table></div></section></div>
<?php require __DIR__.'/_layout_end.php'; ?>
