<?php
require_once __DIR__.'/_common.php'; $adminTitle='Route Management'; checkPostCsrf();
if($_SERVER['REQUEST_METHOD']==='POST'){
 $a=postString('action');$id=postInt('id');
 try{
  if($a==='route_save'){
   $name=postString('route_name');$code=postString('route_code');$start=postString('starting_point');$end=postString('ending_point');$desc=postString('description');$status=postString('status','active');
   if($id)$pdo->prepare("UPDATE routes SET route_name=?,route_code=?,starting_point=?,ending_point=?,description=?,status=? WHERE id=?")->execute([$name,$code,$start,$end,$desc,$status,$id]);
   else{$pdo->prepare("INSERT INTO routes(route_name,route_code,starting_point,ending_point,description,status) VALUES(?,?,?,?,?,?)")->execute([$name,$code,$start,$end,$desc,$status]);$id=(int)$pdo->lastInsertId();}
   adminLog('Route saved','route',$id,$code);flash('success','Route saved.');adminRedirect('routes.php?id='.$id);
  }elseif($a==='stop_save'){
   $rid=postInt('route_id');$sid=postInt('stop_id');$name=postString('stop_name');$order=postInt('stop_order');$lat=$_POST['latitude']!==''?$_POST['latitude']:null;$lng=$_POST['longitude']!==''?$_POST['longitude']:null;
   if($name===''||$order<1)throw new Exception('Stop name and valid order are required.');
   if($sid)$pdo->prepare("UPDATE stops SET stop_name=?,stop_order=?,latitude=?,longitude=? WHERE id=? AND route_id=?")->execute([$name,$order,$lat,$lng,$sid,$rid]);
   else{$pdo->prepare("INSERT INTO stops(route_id,stop_name,stop_order,latitude,longitude) VALUES(?,?,?,?,?)")->execute([$rid,$name,$order,$lat,$lng]);}
   adminLog('Stop saved','route',$rid,$name);flash('success','Stop saved.');adminRedirect('routes.php?id='.$rid);
  }elseif($a==='stop_delete'){$rid=postInt('route_id');$sid=postInt('stop_id');$pdo->prepare("DELETE FROM stops WHERE id=? AND route_id=?")->execute([$sid,$rid]);$n=0;$st=$pdo->prepare("SELECT id FROM stops WHERE route_id=? ORDER BY stop_order,id");$st->execute([$rid]);foreach($st->fetchAll() as $row){$pdo->prepare("UPDATE stops SET stop_order=? WHERE id=?")->execute([++$n,$row['id']]);} adminLog('Stop removed','route',$rid);flash('success','Stop removed.');adminRedirect('routes.php?id='.$rid);}
  elseif(in_array($a,['up','down'],true)){ $rid=postInt('route_id');$sid=postInt('stop_id');$st=$pdo->prepare("SELECT id,stop_order FROM stops WHERE id=? AND route_id=?");$st->execute([$sid,$rid]);$cur=$st->fetch();if($cur){$op=$a==='up'?'<':'>'; $st=$pdo->prepare("SELECT id,stop_order FROM stops WHERE route_id=? AND stop_order ".($a==='up'?'<?':'>?')." ORDER BY stop_order ".($a==='up'?'DESC':'ASC')." LIMIT 1");$st->execute([$rid,$cur['stop_order']]);$other=$st->fetch();if($other){$pdo->prepare("UPDATE stops SET stop_order=0 WHERE id=?")->execute([$sid]);$pdo->prepare("UPDATE stops SET stop_order=? WHERE id=?")->execute([$cur['stop_order'],$other['id']]);$pdo->prepare("UPDATE stops SET stop_order=? WHERE id=?")->execute([$other['stop_order'],$sid]);}} adminRedirect('routes.php?id='.$rid);}
  elseif($a==='toggle'){$pdo->prepare("UPDATE routes SET status=IF(status='active','inactive','active') WHERE id=?")->execute([$id]);adminLog('Route status changed','route',$id);flash('success','Route status updated.');adminRedirect('routes.php?id='.$id);}
 }catch(Throwable $e){flash('error',$e instanceof PDOException?'Could not save. Check unique route code/order values.':$e->getMessage());adminRedirect('routes.php'.($id?'?id='.$id:''));}
}
$routes=$pdo->query("SELECT * FROM routes ORDER BY id DESC")->fetchAll();$selected=null;$stops=[];$editStop=null;$editRoute=null;
if(isset($_GET['id'])){$rid=(int)$_GET['id'];$st=$pdo->prepare("SELECT * FROM routes WHERE id=?");$st->execute([$rid]);$selected=$st->fetch();$editRoute=$selected;if($selected){$st=$pdo->prepare("SELECT * FROM stops WHERE route_id=? ORDER BY stop_order,id");$st->execute([$rid]);$stops=$st->fetchAll();}}
if(isset($_GET['edit_stop'])&&$selected){$st=$pdo->prepare("SELECT * FROM stops WHERE id=? AND route_id=?");$st->execute([(int)$_GET['edit_stop'],$selected['id']]);$editStop=$st->fetch();}
require __DIR__.'/_layout.php';
?>
<div class="admin-page-head"><div><span class="admin-kicker">NETWORK</span><h2>Routes & Stops</h2><p>Manage route records and the coordinates used by passenger Leaflet maps.</p></div></div>
<div class="admin-grid-2">
<section class="admin-panel"><div class="admin-panel-head"><h3><?= $editRoute?'Edit Route':'Add Route' ?></h3></div><form method="post" class="admin-form"><input type="hidden" name="csrf_token" value="<?= e(csrfToken()) ?>"><input type="hidden" name="action" value="route_save"><input type="hidden" name="id" value="<?= (int)($editRoute['id']??0) ?>"><label>Route Name<input required name="route_name" value="<?= e($editRoute['route_name']??'') ?>"></label><label>Route Code<input required name="route_code" value="<?= e($editRoute['route_code']??'') ?>"></label><label>Starting Point<input required name="starting_point" value="<?= e($editRoute['starting_point']??'') ?>"></label><label>Ending Point<input required name="ending_point" value="<?= e($editRoute['ending_point']??'') ?>"></label><label>Description<textarea name="description"><?= e($editRoute['description']??'') ?></textarea></label><label>Status<select name="status"><option value="active" <?= ($editRoute['status']??'active')==='active'?'selected':'' ?>>active</option><option value="inactive" <?= ($editRoute['status']??'')==='inactive'?'selected':'' ?>>inactive</option></select></label><button class="admin-btn">Save Route</button></form></section>
<section class="admin-panel"><div class="admin-panel-head"><h3>Route list</h3></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Route</th><th>From → To</th><th>Status</th><th>Stops</th><th></th></tr></thead><tbody><?php foreach($routes as $r): ?><tr><td><strong><?= e($r['route_code']) ?></strong><small><?= e($r['route_name']) ?></small></td><td><?= e($r['starting_point'].' → '.$r['ending_point']) ?></td><td><?= statusBadge($r['status']) ?></td><td><?= count($r['id']==($selected['id']??0)?$stops:[]) ?></td><td><a class="admin-link-btn" href="?id=<?= $r['id'] ?>">Manage</a></td></tr><?php endforeach; ?></tbody></table></div></section>
</div>
<?php if($selected): ?>
<section class="admin-panel"><div class="admin-panel-head"><div><span class="admin-kicker"><?= e($selected['route_code']) ?></span><h3><?= e($selected['route_name']) ?> — Stops</h3></div><a href="routes.php">Clear selection</a></div>
<div class="admin-stop-editor"><form method="post" class="admin-form compact"><input type="hidden" name="csrf_token" value="<?= e(csrfToken()) ?>"><input type="hidden" name="action" value="stop_save"><input type="hidden" name="route_id" value="<?= $selected['id'] ?>"><input type="hidden" name="stop_id" value="<?= (int)($editStop['id']??0) ?>"><label>Stop Name<input required name="stop_name" value="<?= e($editStop['stop_name']??'') ?>"></label><label>Order<input required type="number" min="1" name="stop_order" value="<?= e($editStop['stop_order']??(count($stops)+1)) ?>"></label><label>Latitude<input type="number" step="0.0000001" name="latitude" value="<?= e($editStop['latitude']??'') ?>"></label><label>Longitude<input type="number" step="0.0000001" name="longitude" value="<?= e($editStop['longitude']??'') ?>"></label><button class="admin-btn"><?= $editStop?'Save Stop':'Add Stop' ?></button></form></div>
<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Order</th><th>Stop</th><th>Coordinates</th><th>Order</th><th>Actions</th></tr></thead><tbody><?php foreach($stops as $s): ?><tr><td><b><?= $s['stop_order'] ?></b></td><td><?= e($s['stop_name']) ?></td><td><?= $s['latitude']!==null?e($s['latitude'].', '.$s['longitude']):'<span class="muted">Not set</span>' ?></td><td><form class="inline-form" method="post"><input type="hidden" name="csrf_token" value="<?= e(csrfToken()) ?>"><input type="hidden" name="route_id" value="<?= $selected['id'] ?>"><input type="hidden" name="stop_id" value="<?= $s['id'] ?>"><button name="action" value="up">↑</button><button name="action" value="down">↓</button></form></td><td class="action-links"><a href="?id=<?= $selected['id'] ?>&edit_stop=<?= $s['id'] ?>">Edit</a><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrfToken()) ?>"><input type="hidden" name="action" value="stop_delete"><input type="hidden" name="route_id" value="<?= $selected['id'] ?>"><input type="hidden" name="stop_id" value="<?= $s['id'] ?>"><button>Remove</button></form></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php endif; ?>
<?php require __DIR__.'/_layout_end.php'; ?>
