<?php
require_once __DIR__.'/_common.php'; $adminTitle='Schedule Management'; checkPostCsrf();
if($_SERVER['REQUEST_METHOD']==='POST'){
 $a=postString('action');$id=postInt('id');
 try{
  if($a==='save'){ $route=postInt('route_id');$bus=postInt('bus_id');$dep=postString('departure_time');$arr=postString('arrival_time');$days=postString('operating_days');$status=postString('status','active');
   if(!$route||!$bus||!$dep||!$arr||$days==='')throw new Exception('Complete all schedule fields.');
   if($id)$pdo->prepare("UPDATE schedules SET route_id=?,bus_id=?,departure_time=?,arrival_time=?,operating_days=?,status=? WHERE id=?")->execute([$route,$bus,$dep,$arr,$days,$status,$id]);
   else{$pdo->prepare("INSERT INTO schedules(route_id,bus_id,departure_time,arrival_time,operating_days,status) VALUES(?,?,?,?,?,?)")->execute([$route,$bus,$dep,$arr,$days,$status]);$id=(int)$pdo->lastInsertId();}
   adminLog('Schedule saved','schedule',$id);flash('success','Schedule saved.');
  }elseif($a==='toggle'){$pdo->prepare("UPDATE schedules SET status=IF(status='active','inactive','active') WHERE id=?")->execute([$id]);adminLog('Schedule status changed','schedule',$id);flash('success','Schedule status updated.');}
 }catch(Throwable $e){flash('error','Could not save schedule: '.$e->getMessage());} adminRedirect('schedules.php');
}
$edit=null;if(isset($_GET['edit'])){$st=$pdo->prepare("SELECT * FROM schedules WHERE id=?");$st->execute([(int)$_GET['edit']]);$edit=$st->fetch();}
$routes=$pdo->query("SELECT id,route_code,route_name FROM routes ORDER BY route_code")->fetchAll();$buses=$pdo->query("SELECT id,bus_number FROM buses ORDER BY bus_number")->fetchAll();$rows=$pdo->query("SELECT s.*,r.route_code,r.route_name,b.bus_number FROM schedules s JOIN routes r ON r.id=s.route_id JOIN buses b ON b.id=s.bus_id ORDER BY s.departure_time")->fetchAll();
require __DIR__.'/_layout.php';
?>
<div class="admin-page-head"><div><span class="admin-kicker">TIMETABLE</span><h2>Schedule Management</h2><p>Changes here are reflected on the passenger schedules page.</p></div></div>
<div class="admin-grid-2"><section class="admin-panel"><div class="admin-panel-head"><h3><?= $edit?'Edit Schedule':'Add Schedule' ?></h3></div><form method="post" class="admin-form"><input type="hidden" name="csrf_token" value="<?= e(csrfToken()) ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><label>Route<select required name="route_id"><?php foreach($routes as $r): ?><option value="<?= $r['id'] ?>" <?= ((int)($edit['route_id']??0)==$r['id'])?'selected':'' ?>><?= e($r['route_code'].' — '.$r['route_name']) ?></option><?php endforeach; ?></select></label><label>Bus<select required name="bus_id"><?php foreach($buses as $b): ?><option value="<?= $b['id'] ?>" <?= ((int)($edit['bus_id']??0)==$b['id'])?'selected':'' ?>><?= e($b['bus_number']) ?></option><?php endforeach; ?></select></label><label>Departure<input required type="time" name="departure_time" value="<?= e($edit['departure_time']??'07:00') ?>"></label><label>Arrival<input required type="time" name="arrival_time" value="<?= e($edit['arrival_time']??'09:00') ?>"></label><label>Operating Days<input required name="operating_days" value="<?= e($edit['operating_days']??'Saturday,Sunday,Monday,Tuesday,Wednesday,Thursday') ?>"></label><label>Status<select name="status"><option value="active" <?= ($edit['status']??'active')==='active'?'selected':'' ?>>active</option><option value="inactive" <?= ($edit['status']??'')==='inactive'?'selected':'' ?>>inactive</option></select></label><button class="admin-btn">Save Schedule</button></form></section>
<section class="admin-panel"><div class="admin-panel-head"><h3>Schedules</h3><span><?= count($rows) ?> records</span></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Route</th><th>Bus</th><th>Time</th><th>Days</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><strong><?= e($r['route_code']) ?></strong><small><?= e($r['route_name']) ?></small></td><td><?= e($r['bus_number']) ?></td><td><?= e(substr($r['departure_time'],0,5).' – '.substr($r['arrival_time'],0,5)) ?></td><td><?= e($r['operating_days']) ?></td><td><?= statusBadge($r['status']) ?></td><td class="action-links"><a href="?edit=<?= $r['id'] ?>">Edit</a><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrfToken()) ?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?= $r['id'] ?>"><button>Toggle</button></form></td></tr><?php endforeach; ?></tbody></table></div></section></div>
<?php require __DIR__.'/_layout_end.php'; ?>
